logging:
  level:
    root: info
    io:
      netty:
        handler:
          ssl: error
    reactor:
      netty:
        http:
          client: error

aggressionStopperSettings:
  httpClientSettings:
    proxy:
      enabled: false
      #HTTP, SOCKS4, SOCKS5
      proxyType: HTTP
      host: 127.0.0.1
      port: 8080
      username:
      password:
      connectTimeoutMillis: 1000
    connectionKeepAlive: true
    connectTimeoutMillis: 1000
    responseTimeoutMillis: 1000
    readTimeoutMillis: 0
    writeTimeoutMillis: 0
  requestCount: 1000
  requestRetryCount: 0
  requestsRepeatCount: 1000000000
  parallelism: 0
  commonExecutionTimeoutMillis: 0
  requestsDelayMillis: 1000
  logEachItemNumber: 20
  threadCount: 0
  uris:
   - https://192.168.0.5
   - https://localhost
   - https://localhost10
